### ISSUE TITLE
Transactions列表Account列的链接url构建bug

### ISSUE THREAD

**Issue by Foorgoo** [Elements-Studio/info-starswap#2]
Account下的url点击应该链接到Address，
但是构建的url是transactions的Hash--0x728a1f4198949c25d290ad575d133e3bf50ecf805c32f90883307a1dc02d1e5a
正确的应该是transactions account的address--0x6b1a630efa3620b1983032313e40d7bb
显示的是“0x72...1e5a”，应该是“0x6b...d7bb”
页面的url是：https://stcscan.io/main/address/0x728a1f4198949c25d290ad575d133e3bf50ecf805c32f90883307a1dc02d1e5a
正确的应该是：https://stcscan.io/main/address/0x6b1a630efa3620b1983032313e40d7bb
如果描述的还不够清楚的话去Account列的链接都点一下就知道了，哈哈~
![image](https://user-images.githubusercontent.com/85097010/170231934-0ba09884-ee00-4004-922b-998f5ad549c7.png)

**Comment by fountainchen** [comment]
感谢反馈，已经修复。
